- name: Reboot
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name Reboot the host and wat for it to come back
      ansible.builtin.reboot:
	     reboot_timeout: 600
         msg: "Reboot triggered by AWX"
